INSERT INTO part_of_speech(abbr, name) VALUES ('v', 'verb');
INSERT INTO part_of_speech(abbr, name) VALUES ('n', 'noun');
INSERT INTO part_of_speech(abbr, name) VALUES ('adj', 'adjective');
INSERT INTO part_of_speech(abbr, name) VALUES ('deter', 'determine');
INSERT INTO part_of_speech(abbr, name) VALUES ('adv', 'adverb');
INSERT INTO part_of_speech(abbr, name) VALUES ('pron', 'pronoun');
INSERT INTO part_of_speech(abbr, name) VALUES ('prep', 'preposition');
INSERT INTO part_of_speech(abbr, name) VALUES ('conj', 'conjunction');
INSERT INTO part_of_speech(abbr, name) VALUES ('inter', 'interjection');